# sudo is required for docker
sudo: required

language: go
go: 
  - 1.14.x 
  - master 
os: 
  - linux 
  - osx 
dist: trusty 

env:
    - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"

services:
    - docker

install:
    - docker pull mysql:5.6
    - go get github.com/golang/lint/golint
    - go get github.com/kisielk/errcheck

# With the "docker" tag enabled on go test invocation (-tags docker)
# the mysql:5.6 docker container will be started
# and the mysql tests will connect to this container
# This requires us to stop the pre-installed mysql server
script:
    - sudo service mysql stop
    - env GO111MODULE=on go build  
    - env GO111MODULE=on go test -v 

after_success:
    - ./update-docs.sh
